baseurl: "https://nefter.js.org"
url: "https://nefter.js.org"

title: Nef                 # Name of website
avatar: ""       # Path of avatar image, to be displayed in the theme's header
description: My blog posts            # Short description, primarily used by search engines
favicon: ""           # Icon displayed in the tab

header_text: Welcome to my blog
header_feature_image: ""
footer_text: Copyright 2021
theme: jekyll-theme-minimal